debug: false
lag_time: 300
lisent_addr: 0.0.0.0
lisent_port: 1081
local:
- 127.0.0.1
- localhost
- ::1
- 10.0.0.0
- 172.16.0.0
- 192.168.0.0
- 114.114.114.114
- 119.29.29.29
- 114.114.115.115
- baidu.com
- qq.com
proxy:
- google.com
- youtube.com
- github.com
- 8.8.8.8
- 8.8.4.4
proxy_addr: 127.0.0.1
proxy_port: 1080
reject: []
route_timeout: 1800
static_dns:
- 119.29.29.29
- 114.114.114.114
static_mode: true
static_route_url: https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt
